Updated code

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -8,38 +8,49 @@ verifyMariaDB()
     echo "Waiting for MariaDB container ${j}g${i} to start"
 
     #Global retry counters
-    maxRetryPrimary=10
-    maxRetry=10
-
-    while [[ ${retVal} != 0 || ${maxRetryPrimary} == 10 ]]
+    maxRetryPrimary=1
+    sleep 5
+    while [[ ${retVal} != 0 ]]
     do
+        echo "Test ${maxRetryPrimary}: ${j}g${i}"
         # If the SQL did not return a proper status
         Status=$(docker container exec -it ${j}g${i} bash -c "mysqladmin -uroot ping")
         if [[ ${Status} == *"mysqld is alive"* ]]; then
             successRetry=1
             maxRetry=1
-            while [[ ${successRetry} < 6 || ${maxRetry} == 10 ]]
+            while [[ ${maxRetry} < 6 ]]
             do
-                docker container exec -it ${j}g${i} mariadb -uroot -e "create database tmp101db; drop database tmp101db;"
-                if [ $? -ne 0 ]; then
+                #docker container exec -it ${j}g${i} mariadb -uroot -e "create database tmp101db; drop database tmp101db;"
+                retryStatus=$(docker container exec -it ${j}g${i} bash -c "mysqladmin -uroot ping")
+                #if [ $? -ne 0 ]; then
+                if [[ ${retryStatus} == *"mysqld is alive"* ]]; then
+                    ((successRetry=successRetry+1))
+                    echo -ne "."
+                    sleep 1
+                else
                     echo "MariaDB on ${j}g${i} is NOT available"
                     sleep 1
                     echo "Test RESET: Retrying MariaDB availability on ${j}g${i}"
                     successRetry=1
-                else
-                    echo -ne "."
-                    ((successRetry=successRetry+1))
-                    sleep 1
                 fi
                 ((maxRetry=maxRetry+1))
             done
             echo ""
-            retVal=0
+            if [ ${successRetry} -gt 5 ]; then
+                retVal=0
+            else
+                retVal=1
+            fi
         else
             echo "Test ${maxRetryPrimary}: Container ${j}g${i} ping failed!"
             sleep 5
         fi
         ((maxRetryPrimary=maxRetryPrimary+1))
+        if [[ ${maxRetryPrimary} == 10 ]]; then
+            echo "Failed to validate node ${j}g${i} ! ! !"
+            echo "Aborting!"
+            exit 0
+        fi
     done
     echo "Container ${j}g${i} Status Verified"
     echo ""
@@ -52,7 +63,7 @@ serverStart()
     retVal=1
     docker container start ${j}g${i}
     verifyMariaDB ${j} ${i}
-    docker container exec ${j}g${i} mariadb -uroot < /tmp/init/${j}-gtid-setup.sql
+    docker container exec ${j}g${i} bash -c "mariadb -uroot < /tmp/init/${j}-gtid-setup.sql"
 }
 
 clear
@@ -82,8 +93,6 @@ do
 done
 
 echo "Setting Up Galera"
-docker-compose stop
-sleep 3
 for i in 1 2 3
 do
     for j in dc dr
@@ -91,14 +100,27 @@ do
         echo "Pushing config for ${j}-node${i}"
         docker cp ./config/${j}-galera-${i}.cnf ${j}g${i}:/etc/mysql/mariadb.conf.d/60-galera.cnf
         docker cp ./config/${j}-server-${i}.cnf ${j}g${i}:/etc/mysql/mariadb.conf.d/50-server.cnf
-        serverStart ${j} ${i}
+        #serverStart ${j} ${i}
     done
 done
+echo "Restarting Cluster one last time"
+docker-compose restart
+sleep 3
 cd ..
 
 echo "Cluster restarted, setting up MaxScale"
 cd maxscale
 docker-compose up --detach --build
 echo "MaxScale up and ready"
+
+for i in 1 2 3
+do
+    for j in dc dr
+    do
+        echo "Setting up GTID for ${j}g${i}"
+        verifyMariaDB ${j} ${i}
+        docker container exec ${j}g${i} bash -c "mariadb -uroot < /tmp/init/${j}-gtid-setup.sql"
+    done
+done
 
 cd ${CurrentFolder}
