I Refactori you 3000

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,4 +1,61 @@
 #!/bin/bash
+
+verifyMariaDB()
+{
+    j=$1
+    i=$2
+    retVal=1
+    echo "Waiting for MariaDB container ${j}g${i} to start"
+
+    #Global retry counters
+    maxRetryPrimary=10
+    maxRetry=10
+
+    while [[ ${retVal} != 0 || ${maxRetryPrimary} == 10 ]]
+    do
+        # If the SQL did not return a proper status
+        Status=$(docker container exec -it ${j}g${i} bash -c "mysqladmin -uroot ping")
+        if [[ ${Status} == *"mysqld is alive"* ]]; then
+            successRetry=1
+            maxRetry=1
+            while [[ ${successRetry} < 6 || ${maxRetry} == 10 ]]
+            do
+                docker container exec -it ${j}g${i} mariadb -uroot -e "create database tmp101db; drop database tmp101db;"
+                if [ $? -ne 0 ]; then
+                    echo "MariaDB on ${j}g${i} is NOT available"
+                    sleep 1
+                    echo "Test RESET: Retrying MariaDB availability on ${j}g${i}"
+                    successRetry=1
+                else
+                    echo -ne "."
+                    ((successRetry=successRetry+1))
+                    sleep 1
+                fi
+                ((maxRetry=maxRetry+1))
+            done
+            echo ""
+            retVal=0
+        else
+            echo "Test ${maxRetryPrimary}: Container ${j}g${i} ping failed!"
+            sleep 5
+        fi
+        ((maxRetryPrimary=maxRetryPrimary+1))
+    done
+    echo "Container ${j}g${i} Status Verified"
+    echo ""
+}
+
+serverStart()
+{
+    j=$1
+    i=$2
+    retVal=1
+    docker container start ${j}g${i}
+    verifyMariaDB ${j} ${i}
+    docker container exec ${j}g${i} mariadb -uroot < /tmp/init/${j}-gtid-setup.sql
+}
+
+clear
 CurrentFolder=$(pwd)
 
 cd maxscale
@@ -9,36 +66,35 @@ cd ..
 
 echo "y" | docker volume prune
 
-sleep 3
-
 cd galera
 echo "Building MariaDB servers"
 
 docker-compose up --detach --build
-sleep 3
 
 echo "Copying the config files for the cluster and server"
-for i in 3 2 1
+for i in 1 2 3
+do
+    for j in dc dr
+    do
+        verifyMariaDB ${j} ${i}
+        docker container exec ${j}g${i} bash -c "mariadb -uroot < /tmp/init/01.sql"
+    done
+done
+
+echo "Setting Up Galera"
+docker-compose stop
+sleep 3
+for i in 1 2 3
 do
     for j in dc dr
     do
         echo "Pushing config for ${j}-node${i}"
         docker cp ./config/${j}-galera-${i}.cnf ${j}g${i}:/etc/mysql/mariadb.conf.d/60-galera.cnf
         docker cp ./config/${j}-server-${i}.cnf ${j}g${i}:/etc/mysql/mariadb.conf.d/50-server.cnf
+        serverStart ${j} ${i}
     done
 done
-
-echo "Galera/Server config set, restarting cluster"
-docker-compose stop
-sleep 5
-docker-compose start
 cd ..
-
-echo "Waiting for cluster to be available"
-sleep 10
-
-docker container exec dcg1 bash -c "mariadb -uroot < /tmp/init/01.sql"
-docker container exec drg1 bash -c "mariadb -uroot < /tmp/init/01.sql"
 
 echo "Cluster restarted, setting up MaxScale"
 cd maxscale
